/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProgressoRouteImport } from './routes/_authenticated/progresso'
import { Route as AuthenticatedCasoCaseIdRouteImport } from './routes/_authenticated/caso.$caseId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProgressoRoute = AuthenticatedProgressoRouteImport.update({
  id: '/_authenticated/progresso',
  path: '/progresso',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCasoCaseIdRoute = AuthenticatedCasoCaseIdRouteImport.update({
  id: '/_authenticated/caso/$caseId',
  path: '/caso/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/progresso': typeof AuthenticatedProgressoRoute
  '/': typeof AuthenticatedIndexRoute
  '/caso/$caseId': typeof AuthenticatedCasoCaseIdRoute
}
export interface FileRoutesByTo {
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/progresso': typeof AuthenticatedProgressoRoute
  '/': typeof AuthenticatedIndexRoute
  '/caso/$caseId': typeof AuthenticatedCasoCaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/progresso': typeof AuthenticatedProgressoRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/caso/$caseId': typeof AuthenticatedCasoCaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/sitemap.xml' | '/progresso' | '/' | '/caso/$caseId'
  fileRoutesByTo: FileRoutesByTo
  to: '/sitemap.xml' | '/progresso' | '/' | '/caso/$caseId'
  id:
    | '__root__'
    | '/sitemap.xml'
    | '/_authenticated/progresso'
    | '/_authenticated/'
    | '/_authenticated/caso/$caseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthenticatedProgressoRoute: typeof AuthenticatedProgressoRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCasoCaseIdRoute: typeof AuthenticatedCasoCaseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/progresso': {
      id: '/_authenticated/progresso'
      path: '/progresso'
      fullPath: '/progresso'
      preLoaderRoute: typeof AuthenticatedProgressoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/caso/$caseId': {
      id: '/_authenticated/caso/$caseId'
      path: '/caso/$caseId'
      fullPath: '/caso/$caseId'
      preLoaderRoute: typeof AuthenticatedCasoCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthenticatedProgressoRoute: AuthenticatedProgressoRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCasoCaseIdRoute: AuthenticatedCasoCaseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
