/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProgressoRouteImport } from './routes/progresso'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasoCaseIdRouteImport } from './routes/caso.$caseId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressoRoute = ProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasoCaseIdRoute = CasoCaseIdRouteImport.update({
  id: '/caso/$caseId',
  path: '/caso/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/progresso': typeof ProgressoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/caso/$caseId': typeof CasoCaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/progresso': typeof ProgressoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/caso/$caseId': typeof CasoCaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/progresso': typeof ProgressoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/caso/$caseId': typeof CasoCaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/progresso' | '/sitemap.xml' | '/caso/$caseId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/progresso' | '/sitemap.xml' | '/caso/$caseId'
  id: '__root__' | '/' | '/progresso' | '/sitemap.xml' | '/caso/$caseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProgressoRoute: typeof ProgressoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CasoCaseIdRoute: typeof CasoCaseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progresso': {
      id: '/progresso'
      path: '/progresso'
      fullPath: '/progresso'
      preLoaderRoute: typeof ProgressoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caso/$caseId': {
      id: '/caso/$caseId'
      path: '/caso/$caseId'
      fullPath: '/caso/$caseId'
      preLoaderRoute: typeof CasoCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProgressoRoute: ProgressoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CasoCaseIdRoute: CasoCaseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
